project:
  type: website
  output-dir: docs

website:
  title: "Isabelle M. Gibson"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: Final Project GVPT 729B.qmd
        text: "Final Project GVPT 729B"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
